services:
  pstock-frontend:
    image: pstock-frontend:latest
    hostname: pstock-frontend
    container_name: pstock-frontend
    ports:
      - 4200:80
    working_dir: /app
    volumes:
     - ./src/assets:/app/src/assets
    environment:
      API_URL: ${API_URL}
    links:
      - pstock-backend
  pstock-backend:
    image: pstock-backend:latest
    hostname: pstock-backend
    container_name: pstock-backend
    ports:
      - 3000:3001
    working_dir: /app
    volumes:
      - ./images:/app/images
    environment:
      PORT: 3001
      ORIGINS: ${ORIGINS}
      DBHOST: ${DBHOST}
      DBPORT: ${DBPORT}
      PYTHON_EX: ${PYTHON_EX}
  laputabasededatos:
    image: postgres
    container_name: laputabasededatos
    restart: always
    ports:
      - 4000:5432
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
