services:
  pstock-frontend:
    image: pstock-frontend:0.0.1
    hostname: pstock-frontend
    container_name: pstock-frontend
    ports:
      - 4200:80
    working_dir: /app
    volumes:
     - ~\desarrollo\angular\eseoshe\src\assets:/app/src/assets
    environment:
      API: http://pstock-backend:8080/pestock
    links:
      - pstock-backend
  pstock-backend:
    image: pstock-backend:0.0.1
    hostname: pstock-backend
    container_name: pstock-backend
    ports:
      - 3000:3001
    working_dir: /app
    volumes:
      - ~\desarrollo\express\pestock-backend\images:/app/images
    environment:
      PORT: 3001
      ORIGINS: http://localhost:4200
      DBHOST: laputabasededatos
      DBPORT: 5432
  laputabasededatos:
    image: postgres
    container_name: laputabasededatos
    restart: always
    ports:
      - 4000:5432
    volumes:
      - ~\desarrollo\express\pestock-backend\eldump.sql:/docker-entrypoint-initdb.d/eldump.sql
    environment:
      POSTGRES_PASSWORD: Cashimba01
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres